<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>disabler</AssemblyName>
    <RootNamespace>disabler</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UAssetAPI" Version="1.1.0" />
  </ItemGroup>

</Project>
