// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPackets(arg1, arg2) {
  return window['go']['main']['App']['ExportPackets'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
