// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSelect():Promise<string>;

export function BoardConnected():Promise<boolean>;

export function ConnectBoard(arg1:string):Promise<void>;

export function CurrentPort():Promise<string>;

export function DetectPort():Promise<string>;

export function DisconnectBoard():Promise<void>;

export function SendKey(arg1:string):Promise<void>;
