// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSelect() {
  return window['go']['main']['Arduino']['AutoSelect']();
}

export function BoardConnected() {
  return window['go']['main']['Arduino']['BoardConnected']();
}

export function ConnectBoard(arg1) {
  return window['go']['main']['Arduino']['ConnectBoard'](arg1);
}

export function CurrentPort() {
  return window['go']['main']['Arduino']['CurrentPort']();
}

export function DetectPort() {
  return window['go']['main']['Arduino']['DetectPort']();
}

export function DisconnectBoard() {
  return window['go']['main']['Arduino']['DisconnectBoard']();
}

export function SendKey(arg1) {
  return window['go']['main']['Arduino']['SendKey'](arg1);
}
