// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsCapturing() {
  return window['go']['main']['Capture']['IsCapturing']();
}

export function SetAnimMask(arg1, arg2) {
  return window['go']['main']['Capture']['SetAnimMask'](arg1, arg2);
}

export function SetAuto(arg1, arg2, arg3) {
  return window['go']['main']['Capture']['SetAuto'](arg1, arg2, arg3);
}

export function SetCasterFilter(arg1) {
  return window['go']['main']['Capture']['SetCasterFilter'](arg1);
}

export function SetCasterMask(arg1, arg2, arg3) {
  return window['go']['main']['Capture']['SetCasterMask'](arg1, arg2, arg3);
}

export function SetCatalog(arg1) {
  return window['go']['main']['Capture']['SetCatalog'](arg1);
}

export function SetCharacterNames(arg1) {
  return window['go']['main']['Capture']['SetCharacterNames'](arg1);
}

export function SetDecode(arg1) {
  return window['go']['main']['Capture']['SetDecode'](arg1);
}

export function SetInspect(arg1, arg2) {
  return window['go']['main']['Capture']['SetInspect'](arg1, arg2);
}

export function SetSessionRecord(arg1) {
  return window['go']['main']['Capture']['SetSessionRecord'](arg1);
}

export function SetSkillSwap(arg1, arg2, arg3) {
  return window['go']['main']['Capture']['SetSkillSwap'](arg1, arg2, arg3);
}

export function StartCapture(arg1) {
  return window['go']['main']['Capture']['StartCapture'](arg1);
}

export function StopCapture() {
  return window['go']['main']['Capture']['StopCapture']();
}

export function UpdateCapture(arg1) {
  return window['go']['main']['Capture']['UpdateCapture'](arg1);
}
