// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';

export function IsCapturing():Promise<boolean>;

export function SetAnimMask(arg1:boolean,arg2:number):Promise<void>;

export function SetAuto(arg1:boolean,arg2:number,arg3:number):Promise<void>;

export function SetCasterFilter(arg1:number):Promise<void>;

export function SetCasterMask(arg1:boolean,arg2:number,arg3:number):Promise<void>;

export function SetCatalog(arg1:Array<capture.CatalogEntry>):Promise<void>;

export function SetCharacterNames(arg1:Array<string>):Promise<void>;

export function SetDecode(arg1:boolean):Promise<void>;

export function SetInspect(arg1:boolean,arg2:boolean):Promise<void>;

export function SetSessionRecord(arg1:boolean):Promise<string>;

export function StartCapture(arg1:Array<capture.SkillSpeed>):Promise<void>;

export function StopCapture():Promise<void>;

export function UpdateCapture(arg1:Array<capture.SkillSpeed>):Promise<void>;
