// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Attached() {
  return window['go']['main']['MemRead']['Attached']();
}

export function Detach() {
  return window['go']['main']['MemRead']['Detach']();
}

export function ListAionProcesses() {
  return window['go']['main']['MemRead']['ListAionProcesses']();
}

export function ProcessName() {
  return window['go']['main']['MemRead']['ProcessName']();
}

export function ReadBlock(arg1, arg2) {
  return window['go']['main']['MemRead']['ReadBlock'](arg1, arg2);
}

export function ReadFloatAt(arg1) {
  return window['go']['main']['MemRead']['ReadFloatAt'](arg1);
}

export function ReadSpec(arg1) {
  return window['go']['main']['MemRead']['ReadSpec'](arg1);
}

export function ReadTypedAt(arg1, arg2) {
  return window['go']['main']['MemRead']['ReadTypedAt'](arg1, arg2);
}

export function ScanCount() {
  return window['go']['main']['MemRead']['ScanCount']();
}

export function ScanFloatRange(arg1, arg2) {
  return window['go']['main']['MemRead']['ScanFloatRange'](arg1, arg2);
}

export function ScanList(arg1) {
  return window['go']['main']['MemRead']['ScanList'](arg1);
}

export function ScanMode() {
  return window['go']['main']['MemRead']['ScanMode']();
}

export function ScanNew(arg1, arg2, arg3, arg4) {
  return window['go']['main']['MemRead']['ScanNew'](arg1, arg2, arg3, arg4);
}

export function ScanNext(arg1, arg2, arg3) {
  return window['go']['main']['MemRead']['ScanNext'](arg1, arg2, arg3);
}

export function ScanRemove(arg1) {
  return window['go']['main']['MemRead']['ScanRemove'](arg1);
}

export function ScanReset() {
  return window['go']['main']['MemRead']['ScanReset']();
}

export function SetProcessName(arg1) {
  return window['go']['main']['MemRead']['SetProcessName'](arg1);
}

export function Status() {
  return window['go']['main']['MemRead']['Status']();
}
