// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memread} from '../models';
import {main} from '../models';

export function Attached():Promise<boolean>;

export function Detach():Promise<void>;

export function ListAionProcesses():Promise<Array<memread.ProcInfo>>;

export function ProcessName():Promise<string>;

export function ReadBlock(arg1:string,arg2:number):Promise<main.BlockResult>;

export function ReadFloatAt(arg1:string):Promise<number>;

export function ReadSpec(arg1:string):Promise<main.SpecResult>;

export function ReadTypedAt(arg1:string,arg2:string):Promise<number>;

export function ScanCount():Promise<number>;

export function ScanFloatRange(arg1:number,arg2:number):Promise<main.ScanResult>;

export function ScanList(arg1:number):Promise<Array<memread.ScanHit>>;

export function ScanMode():Promise<string>;

export function ScanNew(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ScanResult>;

export function ScanNext(arg1:string,arg2:number,arg3:number):Promise<main.ScanResult>;

export function ScanRemove(arg1:string):Promise<number>;

export function ScanReset():Promise<void>;

export function SetProcessName(arg1:string):Promise<void>;

export function Status():Promise<memread.Status>;
