// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyNIC() {
  return window['go']['main']['Mod']['ApplyNIC']();
}

export function ApplyTCP() {
  return window['go']['main']['Mod']['ApplyTCP']();
}

export function DetectGamePath() {
  return window['go']['main']['Mod']['DetectGamePath']();
}

export function IntroStatus() {
  return window['go']['main']['Mod']['IntroStatus']();
}

export function NICStatus() {
  return window['go']['main']['Mod']['NICStatus']();
}

export function RemoveIntro() {
  return window['go']['main']['Mod']['RemoveIntro']();
}

export function RestoreIntro() {
  return window['go']['main']['Mod']['RestoreIntro']();
}

export function RevertNIC() {
  return window['go']['main']['Mod']['RevertNIC']();
}

export function RevertTCP() {
  return window['go']['main']['Mod']['RevertTCP']();
}

export function TCPStatus() {
  return window['go']['main']['Mod']['TCPStatus']();
}
