// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gamemod} from '../models';

export function ApplyNIC():Promise<gamemod.TweakStatus>;

export function ApplySkillEffect():Promise<gamemod.SkillEffectInfo>;

export function ApplyTCP():Promise<gamemod.TweakStatus>;

export function IntroStatus():Promise<gamemod.Status>;

export function NICStatus():Promise<gamemod.TweakStatus>;

export function RemoveIntro():Promise<gamemod.Status>;

export function RestoreIntro():Promise<gamemod.Status>;

export function RevertNIC():Promise<gamemod.TweakStatus>;

export function RevertSkillEffect():Promise<gamemod.SkillEffectInfo>;

export function RevertTCP():Promise<gamemod.TweakStatus>;

export function SkillEffectStatus():Promise<gamemod.SkillEffectInfo>;

export function TCPStatus():Promise<gamemod.TweakStatus>;
