// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:boolean,arg4:Array<string>):Promise<void>;

export function Disconnect():Promise<void>;

export function IsConnected():Promise<boolean>;

export function SetupServer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;
