// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Oversize']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect() {
  return window['go']['main']['Oversize']['Disconnect']();
}

export function IsConnected() {
  return window['go']['main']['Oversize']['IsConnected']();
}

export function SetupServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Oversize']['SetupServer'](arg1, arg2, arg3, arg4);
}
