// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screen} from '../models';

export function CaptureRectPreview(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function SampleRects(arg1:Array<screen.Rect>):Promise<Array<number>>;

export function SkillbarRunning():Promise<boolean>;

export function StartSkillbar(arg1:Array<screen.Rect>,arg2:number,arg3:number):Promise<void>;

export function StopSkillbar():Promise<void>;
