// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureRectPreview(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Screen']['CaptureRectPreview'](arg1, arg2, arg3, arg4);
}

export function SampleRects(arg1) {
  return window['go']['main']['Screen']['SampleRects'](arg1);
}

export function SkillbarRunning() {
  return window['go']['main']['Screen']['SkillbarRunning']();
}

export function StartSkillbar(arg1, arg2, arg3) {
  return window['go']['main']['Screen']['StartSkillbar'](arg1, arg2, arg3);
}

export function StopSkillbar() {
  return window['go']['main']['Screen']['StopSkillbar']();
}
